name: API & UI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # ---------- API Tests with Newman ----------
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Newman + Reporter
        run: npm install -g newman newman-reporter-html

      - name: Run Postman Collection
        run: |
          newman run "conduit-postman-collection/Conduit API Tests.postman_collection.json" --reporters cli,html --reporter-html-export report.html

      - name: Upload Newman HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman-report.html

      # ---------- UI Tests with Playwright ----------
      - name: Install project dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
